GET https://localhost:5002/api/customers/ HTTP/1.1
###
GET https://localhost:5002/api/customers/?country=Germany HTTP/1.1
###
GET https://localhost:5002/api/customers/?country=Germany HTTP/1.1
Accept: application/xml
###
GET https://localhost:5002/api/customers/LELWT HTTP/1.1
###
GET https://localhost:5002/api/customers/abcxy HTTP/1.1